productsSample = [
    # Phần I: Vai trò và Mục tiêu của Quản trị Tài chính Doanh nghiệp
    "Trình bày khái niệm tài chính doanh nghiệp xét về hình thức và bản chất.",
    "Quản trị tài chính doanh nghiệp là gì và bao gồm những nhóm quyết định tài chính cơ bản nào?",
    "Mô tả vai trò của giám đốc tài chính như một cầu nối giữa doanh nghiệp và thị trường tài chính.",
    "Ba chính sách tài chính chiến lược mà một giám đốc tài chính phải phân tích và lựa chọn là gì?",
    "Tại sao mục tiêu 'tối đa hóa giá trị công ty' lại được coi là phù hợp hơn mục tiêu 'tối đa hóa lợi nhuận' trong quản trị tài chính hiện đại?",
    "Thị trường tài chính là gì và có những chức năng cơ bản nào?",
    "Kể tên các loại thị trường tài chính dựa trên tiêu chí thời hạn luân chuyển vốn, cơ cấu thị trường và tính chất chuyên môn hóa.",
    "Những tổ chức tài chính nào thường tham gia trên thị trường tài chính?",
    "Phân biệt các công cụ tài chính được giao dịch trên thị trường tiền tệ và thị trường vốn.",
    "Theo tài liệu, học viên cần nghiên cứu những quy định pháp lý quan trọng nào liên quan đến lĩnh vực tài chính doanh nghiệp?",

    # Phần II: Giá trị Thời gian của Tiền
    "Giải thích ba lý do chính tại sao 'một đồng ngày hôm nay có giá trị hơn một đồng trong tương lai'.",
    "Lãi suất (r) có vai trò gì trong việc đo lường giá trị thời gian của tiền tệ?",
    "Phân biệt giữa phương pháp lãi đơn và phương pháp lãi kép. Phương pháp nào được ứng dụng phổ biến trong các quyết định tài chính?",
    "Giá trị tương lai của một khoản tiền (FVn) là gì và công thức tính như thế nào?",
    "Giá trị hiện tại của một khoản tiền (PV) là gì và công thức tính ra sao?",
    "Viết công thức tính giá trị tương lai của một chuỗi tiền tệ bất kỳ phát sinh vào cuối kỳ và đầu kỳ.",
    "Chuỗi tiền tệ đồng nhất (niên kim cố định) là gì?",
    "Trình bày công thức tính giá trị tương lai của một chuỗi tiền tệ đồng nhất trong trường hợp phát sinh cuối kỳ và đầu kỳ.",
    "Viết công thức tính giá trị hiện tại của một chuỗi tiền tệ bất kỳ phát sinh vào cuối kỳ và đầu kỳ.",
    "Trình bày công thức tính giá trị hiện tại của một chuỗi tiền tệ đồng nhất trong trường hợp phát sinh cuối kỳ và đầu kỳ.",
    "Dòng tiền vô hạn là gì và có thể được phân loại như thế nào?",
    "Công thức xác định giá trị hiện tại của một dòng tiền đều vô hạn là gì?",
    "Công thức xác định giá trị hiện tại của một dòng tiền tăng trưởng đều vô hạn là gì?",
    "Mô tả cách tiếp cận để xác định giá trị hiện tại của một dòng tiền tăng trưởng không đều vô hạn.",
    "Hệ số chiết khấu là gì và nó được sử dụng như thế nào trong việc tính giá trị hiện tại?",

    # Phần III: Rủi ro và Tỷ suất sinh lời
    "Rủi ro trong đầu tư tài chính được định nghĩa như thế nào?",
    "Phân biệt rủi ro hệ thống (systematic risk) và rủi ro phi hệ thống (unsystematic risk). Cho ví dụ về các yếu tố gây ra từng loại rủi ro.",
    "Loại rủi ro nào có thể được giảm thiểu thông qua đa dạng hóa danh mục đầu tư?",
    "Rủi ro hệ thống (rủi ro thị trường) được đo lường bằng chỉ tiêu nào?",
    "Tỷ suất sinh lời của một khoản đầu tư phản ánh điều gì?",
    "Viết công thức tính tỷ suất sinh lời của một khoản đầu tư vào chứng khoán trong một năm, dựa trên giá mua, giá bán và tiền lãi nhận được.",
    "Để đo lường rủi ro, người ta thường sử dụng hai tham số nào của phân phối xác suất?",
    "Tỷ suất sinh lời kỳ vọng (r̄) được tính như thế nào?",
    "Phương sai (σ²) và độ lệch chuẩn (σ) được sử dụng để đo lường mức độ phân tán của tỷ suất sinh lời như thế nào?",
    "Tại sao phải sử dụng hệ số biến thiên (CV) khi so sánh rủi ro của hai khoản đầu tư có tỷ suất sinh lời kỳ vọng khác nhau?",
    "Danh mục đầu tư (portfolio) là gì?",
    "Trình bày công thức tính tỷ suất sinh lời kỳ vọng của một danh mục đầu tư (rE).",
    "Rủi ro của một danh mục đầu tư chịu ảnh hưởng của những yếu tố nào ngoài độ lệch chuẩn của các chứng khoán riêng lẻ?",
    "Hiệp phương sai (COV) giữa hai chứng khoán phản ánh điều gì?",
    "Ý nghĩa của hệ số tương quan (PAB) khi có giá trị bằng +1, -1, và 0 là gì?",
    "Hệ số bêta (β) là gì và nó đo lường loại rủi ro nào của một chứng khoán?",
    "Giải thích ý nghĩa của một cổ phiếu khi có hệ số β > 1, β = 1, và β < 1.",
    "Tỷ suất sinh lời mà nhà đầu tư đòi hỏi được cấu thành từ những yếu tố nào?",
    "Trình bày các thành phần trong mô hình định giá tài sản vốn (CAPM): ri = rf + βi (rm – rf).",
    "Đường thị trường chứng khoán (SML) thể hiện mối quan hệ giữa yếu tố nào và được mô tả bằng phương trình nào?",

    # Phần V: Dự báo nhu cầu Tài chính Doanh nghiệp
    "Trình bày 4 bước cơ bản của phương pháp dự báo nhu cầu tài chính theo 'tỷ lệ phần trăm trên doanh thu'.",
    "Những khoản mục nào trong bảng cân đối kế toán thường có quan hệ trực tiếp và chặt chẽ với doanh thu bán hàng?",
    "Nêu các hạn chế của phương pháp P/E trong định giá cổ phiếu.",
    "Nhu cầu vốn cần tài trợ thêm từ bên ngoài (AFN) được xác định như thế nào trong phương pháp tỷ lệ phần trăm trên doanh thu?",
    "Các giả định cơ bản khi áp dụng phương pháp tỷ lệ phần trăm trên doanh thu là gì?",
    "Làm cách nào để điều chỉnh mô hình dự báo khi doanh nghiệp đang hoạt động dưới công suất?",
    "Lợi nhuận giữ lại đóng vai trò như thế nào trong việc tài trợ cho sự tăng trưởng của doanh nghiệp?",
    "Tỷ lệ tăng trưởng bền vững là gì và nó được tính toán như thế nào?",
    "Những yếu tố nào ảnh hưởng đến khả năng tăng trưởng bền vững của một công ty?",
    "Ngoài phương pháp tỷ lệ phần trăm trên doanh thu, bạn có biết phương pháp dự báo tài chính nào khác không?",

    # Phần IX: Hệ thống đòn bẩy trong Doanh nghiệp
    "Đòn bẩy kinh doanh là gì và nó phản ánh mức độ sử dụng loại chi phí nào?",
    "Mức độ ảnh hưởng của đòn bẩy kinh doanh (DOL) đo lường sự thay đổi của chỉ tiêu nào so với sự thay đổi của sản lượng?",
    "Doanh nghiệp có đặc điểm chi phí như thế nào thì có mức độ ảnh hưởng của đòn bẩy kinh doanh lớn?",
    "Đòn bẩy tài chính là gì và nó được sử dụng như một công cụ để khuếch đại chỉ tiêu nào?",
    "Mức độ ảnh hưởng của đòn bẩy tài chính (DFL) phụ thuộc chủ yếu vào yếu tố nào trong cơ cấu vốn của doanh nghiệp?",
    "Việc sử dụng đòn bẩy tài chính có thể mang lại những lợi ích và rủi ro tiềm ẩn nào cho chủ sở hữu?",
    "Đòn bẩy tổng hợp (DTL) phản ánh tác động kết hợp của hai loại đòn bẩy nào?",
    "Trình bày mối quan hệ toán học giữa DOL, DFL và DTL.",
    "Phân tích điểm hòa vốn là gì và tại sao nó lại quan trọng trong việc ra quyết định kinh doanh?",
    "Rủi ro kinh doanh và rủi ro tài chính có mối liên hệ như thế nào với đòn bẩy kinh doanh và đòn bẩy tài chính?",

    # Phần X: Quản trị Vốn kinh doanh của Doanh nghiệp
    "Vốn kinh doanh của doanh nghiệp bao gồm những bộ phận nào?",
    "Vốn cố định là gì và nêu các đặc điểm của vốn cố định.",
    "Khấu hao tài sản cố định là gì và phương pháp khấu hao theo sản lượng phù hợp với loại TSCĐ nào?",
    "Nguyên tắc cốt lõi trong quản trị và sử dụng vốn cố định là gì?",
    "Vốn lưu động là gì và nêu các đặc điểm chu chuyển của vốn lưu động.",
    "Trình bày các phương pháp xác định nhu cầu vốn lưu động.",
    "Mục tiêu chính của quản trị hàng tồn kho là gì?",
    "Mô hình đặt hàng kinh tế (EOQ) được sử dụng để xác định điều gì và dựa trên việc tối thiểu hóa những loại chi phí nào?",
    "Việc duy trì các khoản phải thu (bán chịu) có thể gây ra những chi phí và rủi ro nào cho doanh nghiệp?",
    "Kỳ thu tiền bình quân được tính như thế nào và nó phản ánh hiệu quả của hoạt động nào?",

    # Phần XI: Phân phối lợi nhuận của Doanh nghiệp
    "Theo quy định chung, lợi nhuận sau thuế của doanh nghiệp được sử dụng để làm gì?",
    "Cổ tức là gì và nguồn gốc của cổ tức đến từ đâu?",
    "Cổ tức có thể được chi trả cho cổ đông dưới những hình thức nào?",
    "Nêu ba chỉ tiêu chính được sử dụng để đánh giá chính sách cổ tức của một công ty cổ phần.",
    "Chính sách cổ tức thực chất là việc giải quyết mối quan hệ giữa hai yếu tố nào?",
    "Mục tiêu cuối cùng của một chính sách cổ tức là gì?",
    "Trình bày ưu điểm và hạn chế của hình thức trả cổ tức bằng tiền mặt so với cổ tức bằng cổ phiếu.",
    "Lý thuyết nào cho rằng chính sách cổ tức không có ảnh hưởng đến giá trị của công ty?",
    "Lý thuyết 'Chim trong lồng' (Bird-in-the-hand) giải thích tại sao nhiều nhà đầu tư lại ưa thích nhận cổ tức bằng tiền mặt?",
    "Phân biệt giữa 'Chính sách ổn định cổ tức' và 'Chính sách thặng dư cổ tức'.",

    # Phần XII: Định giá Doanh nghiệp
    "Định giá doanh nghiệp là gì và thường được thực hiện trong những bối cảnh nào?",
    "Kể tên các yếu tố thuộc về môi trường vĩ mô, ngành và nội tại doanh nghiệp có ảnh hưởng đến giá trị doanh nghiệp.",
    "Phương pháp định giá dựa trên tài sản hoạt động dựa trên nguyên tắc nào?",
    "Phân biệt giá trị sổ sách, giá trị thay thế và giá trị thị trường của một tài sản.",
    "Phương pháp dòng tiền chiết khấu (DCF) dựa trên quan niệm cốt lõi nào để xác định giá trị của một doanh nghiệp?",
    "Phân biệt giữa dòng tiền thuần của doanh nghiệp (FCFF) và dòng tiền thuần của chủ sở hữu (FCFE).",
    "Trình bày các bước cơ bản để định giá một doanh nghiệp theo phương pháp chiết khấu dòng tiền.",
    "Tỷ suất chiết khấu phù hợp để sử dụng khi định giá với FCFF và FCFE là gì?",
    "Phương pháp so sánh (phương pháp bội số) hoạt động như thế nào? Chỉ số P/E có ý nghĩa gì trong phương pháp này?",
    "Nêu những hạn chế chính của việc sử dụng phương pháp so sánh trong định giá doanh nghiệp.",
    
    # Câu hỏi từ các Bài tập Tình huống
    "Dựa vào dữ liệu của Bài số 1, hãy tính sản lượng hòa vốn của doanh nghiệp khi chưa đầu tư và sau khi đầu tư.",
    "Dựa vào Bài số 2, hãy tính toán sự thay đổi của sản lượng hòa vốn và lợi nhuận trước lãi vay và thuế (EBIT) trong năm kế hoạch so với năm báo cáo.",
    "Dựa vào các chi phí được liệt kê trong Bài số 3, hãy xác định nguyên giá của tài sản cố định mà công ty ABC dự kiến đầu tư.",
    "Dựa trên các thông tin về dòng tiền và chi phí sử dụng vốn trong Bài số 14, hãy cho biết dự án có nên được chấp thuận đầu tư hay không theo tiêu chuẩn giá trị hiện tại thuần (NPV)?",
    "Dựa vào dữ liệu trong Bài số 15, hãy xác định chi phí sử dụng vốn bình quân gia quyền (WACC) của công ty Ezzell."
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]